name: sample github actions

on:
  push:
    branches:
      - main

jobs:
  install-dependencies-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Export static file
        run: |
          mkdir out
          cp -r .next/* out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: out
          retention-days: 7

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: install-dependencies-and-build

    steps:
      - name: download artifact 
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: output-artifact

      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_REGION: ap-southeast-1
          SOURCE_DIR: output-artifact