name: Sample GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  install-dependencies-and-build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: .next

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Export static file
        run: |
          mkdir out
          cp -r $BUILD_DIR/* out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: out
          retention-days: 7

  upload-to-s3:
    runs-on: ubuntu-latest
    needs: install-dependencies-and-build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: output-artifact

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: your-s3-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-1
          SOURCE_DIR: output-artifact